kind: Deployment
apiVersion: apps/v1
metadata:
  name: veldeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: velpod
  template:
    metadata:
      labels:
        name: velpod
    spec:
      containers:
        - name: vel-1
          image: rahulsgodase/myapp:5
          ports:
            - containerPort: 8080

